### ISSUE TITLE
ボタンの変更

### ISSUE THREAD

**Issue by ohno** [CompPhysSchool/2026#2]
- [x] ひとまずコメントアウト
- [x] リンクが上がり次第、参加申し込みやお問い合わせなどとして利用

https://github.com/CompPhysSchool/2026/blob/3dad4f9d5055103fcb6b6fac89a4d1d41acf030b/index.md?plain=1#L9-L14

```
  actions:
    - theme: brand
      text: 参加申し込み
      link: 
    - theme: alt
      text: お問い合せ
      link: 
```
